sudo: required

services:
- docker

language: bash

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t $CI_REGISTRY_USER/rpi-domoticz-docker .
# push image
- docker login -u="$CI_REGISTRY_USER" -p="$CI_REGISTRY_PASSWORD"    
- docker tag $CI_REGISTRY_USER/rpi-domoticz-docker $CI_REGISTRY_USER/rpi-domoticz-docker:travis
- docker push $CI_REGISTRY_USER/rpi-domoticz-docker:travis
