sudo: required

services:
- docker

language: bash

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t $CI_REGISTRY_USER/rpi-domoticz:latest .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin   
    docker tag $CI_REGISTRY_USER/rpi-domoticz:latest $CI_REGISTRY_USER/rpi-domoticz:latest
    docker push $CI_REGISTRY_USER/rpi-domoticz:latest
  fi
