version: '3.6'

services:
  domoticz:
    container_name: caromoticz-home
    image: domoticz:3.8153
    build:
      context: .
    devices:
      - "/dev/ttyUSBZSTICK"
      - "/dev/ttyUSBRFXCOM"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes/backup/domoticz.db:/root/domoticz/domoticz.db:rw
      - ./volumes/broadlink:/root/domoticz/broadlink:rw
    ports:
      - "8084:8080"
    restart: always
