version: '3.6'

services:
  domoticz:
    container_name: domoticz-home
    image: domoticz:4.9700
    build:
      context: .
    devices:
      - "/dev/ttyUSBZSTICK" 
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes/backup/domoticz.db:/root/domoticz/domoticz.db:rw
    ports:
      - "8084:8080"
    restart: always
