version: '3.6'

services:
  domoticz:
    container_name: domoticz-home
    image: selorbis/domoticz:beta-latest
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes/backup/domoticz.db:/root/domoticz/domoticz.db:rw
    ports:
      - "8085:8080"
    restart: always
