version: '3.6'

services:
  domoticz:
    container_name: domoticz-home
    build:
      context: .    
    volumes:
      - /etc/localtime:/etc/localtime
      - domoticz_config:/config
    ports:
      - "8084:8080"
    restart: always

volumes:
  domoticz_config:
